/* EJERCICIO 1: INTEGRIDAD DE DATOS */
CREATE OR REPLACE TABLE `mm-tse-latam-interviews.challange_florencia.VENTAS_LIMPIA` AS
SELECT 
  CASE 
    WHEN ID_VENTA IS NULL THEN GENERATE_UUID()
    ELSE CAST(ID_VENTA AS STRING)
  END AS ID_VENTA,
  DATE(COALESCE(CREATION_DATE, '2022-01-01')) AS CREATION_DATE,
  CASE 
    WHEN REGEXP_CONTAINS(UPPER(PAIS), r'ARG|AR') THEN 'ARG'
    WHEN REGEXP_CONTAINS(UPPER(PAIS), r'BRA|BR') THEN 'BRA'
    WHEN REGEXP_CONTAINS(UPPER(PAIS), r'MEX|MX') THEN 'MEX'
  END AS PAIS,
  CAST(ID_PRODUCTO AS STRING) AS ID_PRODUCTO,
  PRECIO_MONEDA_LOCAL,
  ABS(CANTIDAD) AS CANTIDAD
FROM `mm-tse-latam-interviews.challange_florencia.ventas_2`
WHERE
  PRECIO_MONEDA_LOCAL IS NOT NULL
  AND CREATION_DATE BETWEEN '2022-01-01' AND '2022-03-31'
  AND ABS(CANTIDAD) > 0;
